apiVersion: apps/v1
kind: Deployment
metadata:
  name: attrflow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: attrflow-elb
  template:
    metadata:
      labels:
        name: attrflow-elb
    spec:
      containers:
        - name: attrflow-app
          image: 466956024587.dkr.ecr.eu-west-2.amazonaws.com/attrition-repo:latest
          imagePullPolicy: Always
          ports:
       
          - containerPort: 5000
            name: inference
            protocol: TCP

          - containerPort: 5001
            name: management
            protocol: TCP

         
         

          env:
          - name: DP_DISABLE_HEALTHCHECKS
            value: "xids"
          resources:
            requests:
              ephemeral-storage: "8Gi"
              cpu: 1000m
              memory: 3000Mi
            limits:
              
              ephemeral-storage: "8Gi"

      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                  - c5.4xlarge
                  - t3.medium
