apiVersion: v1
kind: Service
metadata:
  name: attrflow-elb
spec:
  type: LoadBalancer
  ports:
  - name: port-1

    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: port-2
    port: 5001
    protocol: TCP
    targetPort: 5001

 

  selector:
    name:  attrflow-elb
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-elb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: port-1-e

    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: port-2-e
    port: 5000
    protocol: TCP
    targetPort: 5000

 

  selector:
    name:  grafana-elb

